# Generated by Django 5.1.4 on 2024-12-23 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
    ]
