# Generated by Django 5.1.4 on 2024-12-23 21:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_table_alter_product_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='uploads/products/'),
            preserve_default=False,
        ),
    ]
